### ISSUE TITLE
Developer documentation: Mapping exchange via sparse matrices is not explained

### ISSUE THREAD

**Issue by Huite** [Deltares/imod_coupler#222]
The weights for mapping from one model to another are stored in CSR matrix, and then used to do groupby reductions via a dot product. However, this is not entirely obvious and it's not documented in the dev docs.

**Comment by deltamarnix** [comment]
I believe this ticket should be picked up by someone with a bit more understanding of what is going on. Also, there should be a split in the documentation to be written.

- [ ] Write some documentation on how the the mapping is created by primod. What is the concept behind it? Consider if this should go in the imod coupler documentation or the primod documentation.
- [ ] Write some documentation for developers on how to implement the mapping part, with CSR matrices.
