### ISSUE TITLE
Release process nitpicks

### ISSUE THREAD

**Issue by Huite** [Deltares/imod_coupler#254]
Thoughts and comments:

* I think we decided for Ribasim to synchronize version numbers. I reckon the same reasoning would apply here to imod_coupler and primod.

This section:

> Now submit a pull request which updates the version numbers of the components as needed.
>
> * Remove the -dev suffix from the version number and increase the version number in __init__.py of imod_coupler and pre- processing/primod
>
> For example: __version__ = "0.10.0-dev" -> __version__ = "0.11.0"
>
> * Create a new commit with the updated version number, and push to remote

It's out of order if I interpret it as a list of steps. First it tells me to make a pull request. Then it tells me to make the changes. I would prefer being able to just go along and follow the steps:

* Make a new branch and switch to it.
* Remove the -dev suffix from the version number and increase the version number in __init__.py of imod_coupler and pre- processing/primod. For example: __version__ = "0.10.0-dev" -> __version__ = "0.11.0"
* Create a new commit with the updated version number, and push to remote.
* Create a Pull Request.

Then, when do I create the tags and push them?
I think it would be better to include the tag creation in the list.
Second, do we want to move to 2024.2.0 calver form instead of 2024.02.0 form? I'm not sure if these tags are parsed, but then we should do it for consistency with Ribasim (since we're the same set of people).

**Comment by Hofer-Julian** [comment]
> It's out of order if I interpret it as a list of steps. First it tells me to make a pull request. Then it tells me to make the changes. I would prefer being able to just go along and follow the steps:

Let's just drop the postfix.

> Second, do we want to move to 2024.2.0 calver form instead of 2024.02.0 form? 

Yes

**Comment by Hofer-Julian** [comment]
I think we also want to align primod and imod_coupler versions (like Ribasim)

**Comment by Huite** [comment]
Closed by: https://github.com/Deltares/iMOD-Documentation/pull/43
