### ISSUE TITLE
primod.RechargeSvatMapping doesn't drop layer dimension

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod_coupler#262]
The RechargeSvatMapping requires a 2D field of active Recharge cells which need to be coupled to SVATs.
The recharge grid can be provided in two ways:

1. A 2D grid with dims (y, x)
2. A 3D grid with dims (layer, y, x), where the layer dimension is length one.

In the latter case, we call xarray ``.drop_vars("layer")``  to drop the layer dimension.
However, I'm getting reports this doesn't actually drop the dimension, but creates an empty dimension, which still needs to be squeezed.
Furthermore I see we have not separate unit tests for this mapping to test its validation.

**Comment by Huite** [comment]
I think the right method here would've been `.squeeze("layer", drop=True)` instead.
