### ISSUE TITLE
add imod_coupler version information to the EXE

### ISSUE THREAD

**Issue by FransRoelofsen** [Deltares/imod_coupler#44]
For support purposes it is helpful/necessary that the user knows which version of the couples EXE he/she uses.  The current coupler does not provide info about which version it is.  
A version name just in the EXE name is not enough. Many programs provide a version name/number in the echo (or a logfile). 
> A version name in the echo will do for the Coupler.

**Comment by Hofer-Julian** [comment]
Calling `imodc --version` should do the trick.

In order to get all options, calling `imodc --help` is always a good idea :)

**Comment by FransRoelofsen** [comment]
This is OK but a little bit hidden. Perhaps this calling method is a Python standard but users don't know this is a python executable. For instance, the same call for iMOD_V5_2_X64R.exe will not work.  
For consideration: so perhaps a standard echo line is still helpful. 
Kind regards

**Comment by JoerivanEngelen** [comment]
This --help option is stated in the README.md in this repository, but perhaps we did not document it in the documentation provided with the release. 

A standard echo of the version number can't do much harm in my opinion, as additional help.

**Comment by mjr-deltares** [comment]
@FransRoelofsen: we will start working on more comprehensive version info, for imod_coupler and ideally for the kernels it is running with. I will create an internal (JIRA) issue for that and mention you as reporter.
