### ISSUE TITLE
Download of Intel redistrutable libraries 2018 not available anymore

### ISSUE THREAD

**Issue by jch-deltares** [Deltares/imod_coupler#48]
The solution for the knonw issue _"FileNotFoundError: Could not find module "\path\to\MetaSWAP.dll" (or one of its dependencies). Try using the full path with constructor syntax."_ does not work anymore because the intel libraries of 2018 are not available anymore. However, the 2020 version also works. This is tested on two different server environments. Can the documentation be updated?

**Comment by Hofer-Julian** [comment]
Sounds good
