### ISSUE TITLE
Consider switching from python "toml" package to "tomli"

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod_coupler#61]
The ``toml`` package appears to be abandoned by its maintainer, and getting co-maintainership apparently is a very slow process, despite the package seeing an incredible amount of use.
See for example:
https://github.com/uiri/toml/issues/361

``tomli`` should be a fork that works, from what I read, ``black`` switched to this one already:

https://github.com/hukkin/tomli

Edit: Ah and I see ``tomli`` became a part of the standard library  of Python from 3.11 onwards.
https://github.com/hukkin/tomli#building-a-tomlitomllib-compatibility-layer

**Comment by Hofer-Julian** [comment]
Thanks Joeri, like you I've heard that toml handling will be part of the stdlib.
As soon as 3.11 is out we can drop the toml dependency then :)

**Comment by JoerivanEngelen** [comment]
Yes, alternatively you could consider switching already, and use ``tomli``'s suggested compatibility layer:

https://github.com/hukkin/tomli#building-a-tomlitomllib-compatibility-layer

**Comment by Hofer-Julian** [comment]
> Yes, alternatively you could consider switching already, and use `tomli`'s suggested compatibility layer:

Fine by me.
Would you mind opening an issue at Jira with same component, version and label as [here](https://issuetracker.deltares.nl/browse/IMOD6-828)?

**Comment by JoerivanEngelen** [comment]
Done :-) https://issuetracker.deltares.nl/browse/IMOD6-839

**Comment by Hofer-Julian** [comment]
Thanks :)
